micronaut:
  application:
    name: mnFluxResponseBug

tracing:
  zipkin:
    enabled: true

cassandra:
  default:
    basic:
      contact-points:
        - "${cdb.host}:${cdb.port}"
      load-balancing-policy:
        local-datacenter: "${cdb.datacenter}"
        class: DefaultLoadBalancingPolicy
      request:
        timeout: 5s
        consistency: "LOCAL_QUORUM"

cdb:
  host: "localhost"
  port: 9043
  datacenter: "datacenter1"

netty:
  default:
    allocator:
      max-order: 3
